import type { MineralType, Tag } from '../types';

export type CrystalSystem =
  | 'cubic' | 'hexagonal' | 'trigonal' | 'tetragonal'
  | 'orthorhombic' | 'monoclinic' | 'triclinic' | 'amorphous' | 'none';

export type Luster =
  | 'vitreous' | 'metallic' | 'adamantine' | 'resinous'
  | 'pearly' | 'silky' | 'waxy' | 'earthy' | 'greasy';

export const CRYSTAL_SYSTEM_LABELS: Record<CrystalSystem, string> = {
  cubic: '等軸晶系（立方体のなかま）',
  hexagonal: '六方晶系（六角柱のなかま）',
  trigonal: '三方晶系（三角柱のなかま）',
  tetragonal: '正方晶系（四角柱のなかま）',
  orthorhombic: '斜方晶系（直方体のなかま）',
  monoclinic: '単斜晶系（ななめ四角のなかま）',
  triclinic: '三斜晶系（ゆがんだ形のなかま）',
  amorphous: '非晶質（決まった形がない）',
  none: '該当なし',
};

export const LUSTER_LABELS: Record<Luster, string> = {
  vitreous: 'ガラス光沢',
  metallic: '金属光沢',
  adamantine: 'ダイヤモンド光沢',
  resinous: '樹脂光沢',
  pearly: '真珠光沢',
  silky: '絹糸光沢',
  waxy: 'ろう光沢',
  earthy: '土状光沢',
  greasy: '脂肪光沢',
};

export type GenesisKind = 'magmatic' | 'hydrothermal' | 'metamorphic' | 'sedimentary';

export const GENESIS_LABELS: Record<GenesisKind, string> = {
  magmatic: '火成（マグマ由来）',
  hydrothermal: '熱水鉱床',
  metamorphic: '変成（高温高圧）',
  sedimentary: '堆積・化石化',
};

export interface MineralScience {
  hardness: number | null;
  crystalSystem: CrystalSystem;
  chemicalFormula: string;
  luster: Luster;
  streakColor: string;
  uses: string;
  funFact: string;
}

export interface MineralTierInfo {
  tier: 1 | 2 | 3;
  nextTier: number | null;
  needed: number;
}

export function getMineralTier(count: number, debug?: boolean): MineralTierInfo {
  if (debug) return { tier: 3, nextTier: null, needed: 0 };
  if (count >= 5) return { tier: 3, nextTier: null, needed: 0 };
  if (count >= 3) return { tier: 2, nextTier: 5, needed: 5 - count };
  return { tier: 1, nextTier: 3, needed: 3 - count };
}

export interface MineralDef {
  type: MineralType;
  name: string;
  nameEn: string;
  imageFile?: string; // e.g. 'quartz.jpg'
  rank: number;
  condition: string;
  description: string;
  color: string;
  genesis: GenesisKind;
  formationDepth: number;
  discoveryDepth: number;
  transportReason?: string;
  geoNote: string;
  rewardTag?: Tag;
  rewardEvery?: number;
  requirePerfectWriting?: boolean;
  science?: MineralScience;
}

export const MINERALS: MineralDef[] = [
  {
    type: 'quartz',
    name: '石英',
    nameEn: 'Quartz',
    imageFile: 'quartz.jpg',
    rank: 1,
    condition: '初回正解',
    description: '砂浜の砂にも混ざっている基本の鉱物。透明なものは水晶と呼ばれる。',
    color: '#E8E8E8',
    genesis: 'magmatic',
    formationDepth: 11,
    discoveryDepth: 3,
    transportReason: '深部でできた石英が、風化と運搬で砂として浅層へ集まるため。',
    geoNote: '深部で結晶化した石英が、風化で砕かれて砂層に集まりやすい。',
    science: {
      hardness: 7,
      crystalSystem: 'trigonal',
      chemicalFormula: 'SiO₂',
      luster: 'vitreous',
      streakColor: '白',
      uses: '窓ガラスやレンズの原料',
      funFact: '地殻で2番目に多い鉱物で、砂浜の白っぽいつぶも多くはこれなんだよ。',
    },
  },
  {
    type: 'pyrite',
    name: '黄鉄鉱',
    nameEn: 'Pyrite',
    imageFile: 'pyrite.jpg',
    rank: 2,
    condition: '3回連続正解',
    description: '金色に輝く「愚か者の金」。立方体の結晶が特徴。',
    color: '#CFB53B',
    genesis: 'hydrothermal',
    formationDepth: 6,
    discoveryDepth: 6,
    geoNote: '硫黄を含む熱水が通る場所でできることが多く、泥質の層でも見つかる。',
    science: {
      hardness: 6,
      crystalSystem: 'cubic',
      chemicalFormula: 'FeS₂',
      luster: 'metallic',
      streakColor: '緑黒',
      uses: '硫酸の原料や火打ち石',
      funFact: '昔は火打ち石として使われ、たたくと火花が出ることから「火の石」と呼ばれたよ。',
    },
  },
  {
    type: 'fluorite',
    name: '蛍石',
    nameEn: 'Fluorite',
    imageFile: 'fluorite.jpg',
    rank: 3,
    condition: '部首で正解9回ごと',
    description: 'ブラックライトで光る美しい鉱物。紫、緑、青と色の種類が多い。',
    color: '#9370DB',
    genesis: 'hydrothermal',
    formationDepth: 7,
    discoveryDepth: 7,
    geoNote: '石灰岩中の割れ目に入った熱水から、蛍石の結晶脈が育つ。',
    rewardTag: 'radical',
    rewardEvery: 9,
    science: {
      hardness: 4,
      crystalSystem: 'cubic',
      chemicalFormula: 'CaF₂',
      luster: 'vitreous',
      streakColor: '白',
      uses: '望遠鏡のレンズや製鉄の材料',
      funFact: '暗い場所で紫外線を当てると光るものがあり、暗闇でほのかに輝く姿が美しいよ。',
    },
  },
  {
    type: 'garnet',
    name: 'ザクロ石',
    nameEn: 'Garnet',
    imageFile: 'garnet.jpg',
    rank: 4,
    condition: '対義語・類義語で正解16回ごと',
    description: '宝石としても使われる深い赤色の結晶。変成岩の中に見られる。',
    color: '#8B0000',
    genesis: 'metamorphic',
    formationDepth: 8,
    discoveryDepth: 8,
    geoNote: '高温高圧で岩石が変成すると、示準鉱物としてザクロ石が現れる。',
    rewardTag: 'antonym_synonym',
    rewardEvery: 16,
    science: {
      hardness: 7,
      crystalSystem: 'cubic',
      chemicalFormula: 'Fe₃Al₂(SiO₄)₃',
      luster: 'vitreous',
      streakColor: '白',
      uses: '紙やすりの研磨剤や宝石',
      funFact: '日本では「石榴石」と呼ばれ、ザクロの実に似た真っ赤な粒が集まった姿で産出するよ。',
    },
  },
  {
    type: 'jadeite',
    name: 'ヒスイ輝石',
    nameEn: 'Jadeite',
    imageFile: 'jadeite.jpg',
    rank: 5,
    condition: '書き取りで正解18回ごと',
    description: '日本の国石に選ばれた貴重な鉱物。新潟県糸魚川が有名な産地。',
    color: '#00A86B',
    genesis: 'metamorphic',
    formationDepth: 11,
    discoveryDepth: 2,
    transportReason: '沈み込み帯の深部で生まれた岩片が、断層運動で押し上げられるため。',
    geoNote: '沈み込み帯の深部で生成し、地殻変動で押し上げられて川原で見つかる。',
    rewardTag: 'writing',
    rewardEvery: 18,
    science: {
      hardness: 7,
      crystalSystem: 'monoclinic',
      chemicalFormula: 'NaAlSi₂O₆',
      luster: 'vitreous',
      streakColor: '白',
      uses: '勾玉などの装飾品や宝石',
      funFact: '日本の「国石」に選ばれていて、糸魚川などの限られた場所でしか見つからない貴重な石だよ。',
    },
  },
  {
    type: 'crystal_core',
    name: '結晶核サンプル',
    nameEn: 'Crystal Core',
    rank: 5,
    condition: 'マグマ結晶帯で正解4回ごと',
    description: '最深層で回収する深部サンプル。完成鉱物になる前の「核」を記録する。',
    color: '#FF9A73',
    genesis: 'magmatic',
    formationDepth: 11,
    discoveryDepth: 11,
    geoNote: 'マグマ縁では微小結晶が先に生まれ、冷却条件が整うと大きな鉱物へ成長する。',
    rewardTag: 'writing',
    rewardEvery: 4,
    science: {
      hardness: 7,
      crystalSystem: 'hexagonal',
      chemicalFormula: '(様々)',
      luster: 'vitreous',
      streakColor: '白',
      uses: '研究用の深部サンプル',
      funFact: '鉱物が大きく育つ前の小さな種のような状態で、マントルの近くで静かに誕生を待っているよ。',
    },
  },
  {
    type: 'calcite',
    name: '方解石',
    nameEn: 'Calcite',
    imageFile: 'calcite.jpg',
    rank: 2,
    condition: '石灰岩層で正解10回ごと',
    description: '石灰岩の主成分。へき開がはっきりしていて形の規則性が美しい。',
    color: '#E7ECF5',
    genesis: 'sedimentary',
    formationDepth: 7,
    discoveryDepth: 7,
    geoNote: '石灰岩層の代表鉱物で、海の生物由来の炭酸塩が再結晶してできる。',
    rewardTag: 'on_kun',
    rewardEvery: 10,
    science: {
      hardness: 3,
      crystalSystem: 'trigonal',
      chemicalFormula: 'CaCO₃',
      luster: 'vitreous',
      streakColor: '白',
      uses: 'セメントやチョークの原料',
      funFact: '無色透明なものは「氷州石」と呼ばれ、文字の上に置くと文字が2重に見える不思議な性質があるよ。',
    },
  },
  {
    type: 'magnetite',
    name: '磁鉄鉱',
    nameEn: 'Magnetite',
    imageFile: 'magnetite.jpg',
    rank: 2,
    condition: '火成岩層で正解10回ごと',
    description: '磁石に引きつけられる代表的な鉄鉱物。砂鉄の主成分として有名。',
    color: '#4A4E56',
    genesis: 'magmatic',
    formationDepth: 10,
    discoveryDepth: 9,
    transportReason: 'マグマ分化で濃集した磁鉄鉱粒が、火成岩の貫入と風化でやや上部層へ集まるため。',
    geoNote: 'マグマの分化で濃集しやすく、火成岩帯で黒色の鉱物粒として産する。',
    rewardTag: 'compound_structure',
    rewardEvery: 10,
    science: {
      hardness: 6,
      crystalSystem: 'cubic',
      chemicalFormula: 'Fe₃O₄',
      luster: 'metallic',
      streakColor: '黒',
      uses: '鉄の原料',
      funFact: '磁石に吸い寄せられる性質があり、天然の磁石として大昔の航海で方角を知るために使われたよ。',
    },
  },
  {
    type: 'chalcopyrite',
    name: '黄銅鉱',
    nameEn: 'Chalcopyrite',
    imageFile: 'chalcopyrite.jpg',
    rank: 3,
    condition: '泥層で正解12回ごと',
    description: '銅の主要鉱石。黄鉄鉱より黄みが強く、表面変色も起きやすい。',
    color: '#D3A74A',
    genesis: 'hydrothermal',
    formationDepth: 6,
    discoveryDepth: 6,
    geoNote: '熱水鉱床で黄鉄鉱や石英脈と共生し、泥質変質帯にも現れやすい。',
    rewardTag: 'reading',
    rewardEvery: 12,
    science: {
      hardness: 4,
      crystalSystem: 'tetragonal',
      chemicalFormula: 'CuFeS₂',
      luster: 'metallic',
      streakColor: '緑黒',
      uses: '銅の最も重要な原料',
      funFact: '表面が酸化すると虹色に輝くことがあり、その美しさから「ピーコック・オア」とも呼ばれるよ。',
    },
  },
  {
    type: 'olivine',
    name: '橄欖石',
    nameEn: 'Olivine',
    imageFile: 'olivine.jpg',
    rank: 2,
    condition: '書き取り正解8回ごと',
    description: 'マントルを代表する鉱物。オリーブ色の結晶で「かんらん石」と呼ぶ。',
    color: '#89B54A',
    genesis: 'magmatic',
    formationDepth: 11,
    discoveryDepth: 10,
    transportReason: '深部由来の結晶が、火山噴出物に乗って上部層へ運ばれるため。',
    geoNote: '超塩基性岩やマントル起源岩に多く、深部由来を示す重要鉱物。',
    rewardTag: 'writing',
    rewardEvery: 8,
    science: {
      hardness: 7,
      crystalSystem: 'orthorhombic',
      chemicalFormula: '(Mg,Fe)₂SiO₄',
      luster: 'vitreous',
      streakColor: '白',
      uses: '宝石（ペリドット）や耐火煉瓦',
      funFact: 'マントルの大部分を作っている主要な鉱物で、宇宙から降ってきた隕石の中にも含まれているよ。',
    },
  },
  {
    type: 'apatite',
    name: '燐灰石',
    nameEn: 'Apatite',
    imageFile: 'apatite.jpg',
    rank: 2,
    condition: 'れき層で正解12回ごと',
    description: 'リンを含む鉱物。歯や骨の主成分とも関係し、教育素材に相性が良い。',
    color: '#6FC089',
    genesis: 'magmatic',
    formationDepth: 9,
    discoveryDepth: 4,
    transportReason: '火成岩が風化して砕ける過程で、耐久性の高い燐灰石粒がれき層に残りやすいため。',
    geoNote: '火成岩の副成分として普遍的に含まれ、微量元素解析の指標にもなる。',
    rewardTag: 'jukugo_making',
    rewardEvery: 12,
    science: {
      hardness: 5,
      crystalSystem: 'hexagonal',
      chemicalFormula: 'Ca₅(PO₄)₃(F,Cl,OH)',
      luster: 'vitreous',
      streakColor: '白',
      uses: '肥料の原料や歯の成分',
      funFact: '私たちの歯や骨の主成分と同じ仲間で、実は体の中でも作られているとても身近な鉱物なんだ。',
    },
  },
  {
    type: 'zircon',
    name: 'ジルコン',
    nameEn: 'Zircon',
    imageFile: 'zircon.jpg',
    rank: 3,
    condition: '変成岩層で正解12回ごと',
    description: '小粒でも高硬度。地球の古い年代を測る「地球の時計」として有名。',
    color: '#C9A06D',
    genesis: 'magmatic',
    formationDepth: 8,
    discoveryDepth: 8,
    geoNote: '変成作用に強く残留するため、岩石の形成史を追跡する鍵になる。',
    rewardTag: 'antonym_synonym',
    rewardEvery: 12,
    science: {
      hardness: 8,
      crystalSystem: 'tetragonal',
      chemicalFormula: 'ZrSiO₄',
      luster: 'adamantine',
      streakColor: '白',
      uses: '年代測定の資料や宝石',
      funFact: '40億年以上前の結晶も見つかるほど頑丈で、地球の歴史を知るための「タイムカプセル」なんだ。',
    },
  },
  {
    type: 'corundum',
    name: '鋼玉',
    nameEn: 'Corundum',
    imageFile: 'corundum.jpg',
    rank: 5,
    condition: '書き取りで「◎できた」かつ正解20回ごと',
    description: 'モース硬度9の超硬質鉱物。サファイアとルビーは鋼玉の仲間。',
    color: '#5E7FD3',
    genesis: 'metamorphic',
    formationDepth: 8,
    discoveryDepth: 9,
    transportReason: '変成帯で生まれた鋼玉結晶が、地殻変動や接触帯の再配置で上位岩体に取り込まれるため。',
    geoNote: 'Alに富む環境で生成し、高硬度ゆえに耐久性と希少性の象徴になりやすい。',
    rewardTag: 'writing',
    rewardEvery: 20,
    requirePerfectWriting: true,
    science: {
      hardness: 9,
      crystalSystem: 'trigonal',
      chemicalFormula: 'Al₂O₃',
      luster: 'adamantine',
      streakColor: '白',
      uses: '研磨剤や宝石（ルビーなど）',
      funFact: 'ダイヤモンドの次に硬い鉱物で、赤いものはルビー、それ以外の色はサファイアとして大切にされるよ。',
    },
  },
  {
    type: 'topaz',
    name: 'トパーズ',
    nameEn: 'Topaz',
    imageFile: 'topaz.jpg',
    rank: 5,
    condition: '砂岩層で正解14回ごと',
    description: '高硬度で透明感のある宝石鉱物。色幅が広くコレクション性が高い。',
    color: '#E3B75B',
    genesis: 'hydrothermal',
    formationDepth: 5,
    discoveryDepth: 5,
    geoNote: '花崗岩起源の熱水作用や空隙で結晶化し、流体進化の痕跡を残す。',
    rewardTag: 'homophone',
    rewardEvery: 14,
    science: {
      hardness: 8,
      crystalSystem: 'orthorhombic',
      chemicalFormula: 'Al₂SiO₄(F,OH)₂',
      luster: 'vitreous',
      streakColor: '白',
      uses: '宝石や装飾品',
      funFact: '昔は「トパゾス（探し求める）」と呼ばれ、霧に包まれた島で見つかったことが名前の由来だと言われるよ。',
    },
  },
  {
    type: 'beryl',
    name: '緑柱石',
    nameEn: 'Beryl',
    imageFile: 'beryl.jpg',
    rank: 4,
    condition: '変成・火成岩帯で正解15回ごと',
    description: 'エメラルドやアクアマリンを含む鉱物グループ。結晶柱が特徴。',
    color: '#4DAA92',
    genesis: 'magmatic',
    formationDepth: 9,
    discoveryDepth: 9,
    geoNote: 'ペグマタイト環境で長柱状に成長し、元素置換で多彩な宝石種になる。',
    rewardTag: 'three_char_compound',
    rewardEvery: 15,
    science: {
      hardness: 8,
      crystalSystem: 'hexagonal',
      chemicalFormula: 'Be₃Al₂Si₆O₁₈',
      luster: 'vitreous',
      streakColor: '白',
      uses: '宝石（エメラルドなど）',
      funFact: '含まれる不純物によって色が変わり、緑色はエメラルド、水色はアクアマリンという別の宝石になるよ。',
    },
  },
  {
    type: 'malachite',
    name: '孔雀石',
    nameEn: 'Malachite',
    imageFile: 'malachite.jpg',
    rank: 3,
    condition: '泥層で正解18回ごと',
    description: '縞状の緑が美しい二次銅鉱物。磨くと模様が強調される。',
    color: '#2EA06F',
    genesis: 'hydrothermal',
    formationDepth: 6,
    discoveryDepth: 6,
    geoNote: '銅鉱床の酸化帯で藍銅鉱などと共生し、風化指標として扱われる。',
    rewardTag: 'reading',
    rewardEvery: 18,
    science: {
      hardness: 4,
      crystalSystem: 'monoclinic',
      chemicalFormula: 'Cu₂CO₃(OH)₂',
      luster: 'silky',
      streakColor: '淡緑',
      uses: '絵の具の顔料や装飾品',
      funFact: 'クジャクの羽のような模様が美しく、大昔のエジプトではアイシャドーなどの化粧品としても使われたよ。',
    },
  },
  {
    type: 'muscovite',
    name: '白雲母',
    nameEn: 'Muscovite',
    imageFile: 'muscovite.jpg',
    rank: 2,
    condition: '部首で正解12回ごと',
    description: '薄くはがせる雲母。紙のような層状結晶で、光を反射してきらめく。',
    color: '#E9E3D8',
    genesis: 'metamorphic',
    formationDepth: 9,
    discoveryDepth: 8,
    transportReason: '花崗岩や変成岩で生まれた白雲母片が、変成帯の剥離面に集積しやすいため。',
    geoNote: '変成岩や花崗岩中に現れ、板状のへき開が非常に発達する。',
    rewardTag: 'radical',
    rewardEvery: 12,
    science: {
      hardness: 3,
      crystalSystem: 'monoclinic',
      chemicalFormula: 'KAl₂AlSi₃O₁₀(OH)₂',
      luster: 'pearly',
      streakColor: '白',
      uses: '電気の絶縁体や化粧品',
      funFact: '紙のように薄くペラペラとはがれる性質があり、昔はロシアで窓ガラスの代わりに使われていたんだよ。',
    },
  },
  {
    type: 'biotite',
    name: '黒雲母',
    nameEn: 'Biotite',
    imageFile: 'biotite.jpg',
    rank: 2,
    condition: '送りがなで正解10回ごと',
    description: '黒く輝く雲母。薄い板が重なったような見た目で岩石中に目立つ。',
    color: '#3E3433',
    genesis: 'magmatic',
    formationDepth: 9,
    discoveryDepth: 9,
    geoNote: '花崗岩や変成岩に普通に含まれ、岩石組成の目安になる。',
    rewardTag: 'okurigana',
    rewardEvery: 10,
    science: {
      hardness: 3,
      crystalSystem: 'monoclinic',
      chemicalFormula: 'K(Mg,Fe)₃AlSi₃O₁₀(OH,F)₂',
      luster: 'pearly',
      streakColor: '白',
      uses: '地層の年代を調べる資料',
      funFact: '鉄分を多く含むため黒っぽく見え、火成岩の中に黒いキラキラした点として見つけることができるよ。',
    },
  },
  {
    type: 'orthoclase',
    name: '正長石',
    nameEn: 'Orthoclase',
    imageFile: 'orthoclase.jpg',
    rank: 2,
    condition: '音訓で正解14回ごと',
    description: 'ピンク系の長石。花崗岩を作る主要鉱物の一つ。',
    color: '#D7A38D',
    genesis: 'magmatic',
    formationDepth: 9,
    discoveryDepth: 9,
    geoNote: '珪長質マグマから結晶化し、花崗岩の色調を決める。',
    rewardTag: 'on_kun',
    rewardEvery: 14,
    science: {
      hardness: 6,
      crystalSystem: 'monoclinic',
      chemicalFormula: 'KAlSi₃O₈',
      luster: 'vitreous',
      streakColor: '白',
      uses: '陶磁器やガラスの原料',
      funFact: '月の光のように青白く光るものは「ムーンストーン」と呼ばれ、神秘的な宝石として人気があるんだよ。',
    },
  },
  {
    type: 'plagioclase',
    name: '斜長石',
    nameEn: 'Plagioclase',
    imageFile: 'plagioclase.jpg',
    rank: 1,
    condition: '画数で正解10回ごと',
    description: '白色系の長石。火成岩で最もよく見つかる鉱物グループ。',
    color: '#E6E6DE',
    genesis: 'magmatic',
    formationDepth: 9,
    discoveryDepth: 9,
    geoNote: '苦鉄質から珪長質まで幅広い火成岩に含まれる代表鉱物。',
    rewardTag: 'stroke_count',
    rewardEvery: 10,
    science: {
      hardness: 6,
      crystalSystem: 'triclinic',
      chemicalFormula: '(Na,Ca)AlSi₂₋₃O₈',
      luster: 'vitreous',
      streakColor: '白',
      uses: '陶器の釉薬や道路の材料',
      funFact: '地殻の中で最も多く存在する鉱物で、月の表面の白っぽい部分もこの仲間でできていることがわかっているよ。',
    },
  },
  {
    type: 'gypsum',
    name: '石膏',
    nameEn: 'Gypsum',
    imageFile: 'gypsum.jpg',
    rank: 2,
    condition: '部首で正解14回ごと',
    description: 'やわらかい硫酸塩鉱物。石こう像やチョークの材料としても有名。',
    color: '#F3F0EA',
    genesis: 'sedimentary',
    formationDepth: 4,
    discoveryDepth: 4,
    geoNote: '蒸発岩環境で析出し、乾燥した内陸盆地で産出しやすい。',
    rewardTag: 'radical',
    rewardEvery: 14,
    science: {
      hardness: 2,
      crystalSystem: 'monoclinic',
      chemicalFormula: 'CaSO₄·2H₂O',
      luster: 'vitreous',
      streakColor: '白',
      uses: 'ギプスやチョークの材料',
      funFact: '水の成分を含んでいて、爪で傷がつくほどやわらかいよ。砂漠では「サハラのバラ」という花の形になるよ。',
    },
  },
  {
    type: 'anhydrite',
    name: '硬石膏',
    nameEn: 'Anhydrite',
    imageFile: 'anhydrite.jpg',
    rank: 3,
    condition: '送りがなで正解14回ごと',
    description: '石膏と兄弟の硫酸塩鉱物。水和すると石膏へ変わりやすい。',
    color: '#DCD7CF',
    genesis: 'sedimentary',
    formationDepth: 5,
    discoveryDepth: 5,
    geoNote: '高塩分の蒸発岩層で形成され、水との反応履歴を記録する。',
    rewardTag: 'okurigana',
    rewardEvery: 14,
    science: {
      hardness: 4,
      crystalSystem: 'orthorhombic',
      chemicalFormula: 'CaSO₄',
      luster: 'vitreous',
      streakColor: '白',
      uses: 'セメントの添加剤',
      funFact: '石膏から水が抜けたもので、水に触れると少しずつ水を吸い込んで石膏に戻ってしまう不思議な性質があるよ。',
    },
  },
  {
    type: 'talc',
    name: '滑石',
    nameEn: 'Talc',
    imageFile: 'talc.jpg',
    rank: 2,
    condition: '画数で正解12回ごと',
    description: 'モース硬度1の代表。すべすべした手ざわりが特徴。',
    color: '#D8E0D3',
    genesis: 'metamorphic',
    formationDepth: 8,
    discoveryDepth: 8,
    geoNote: '超塩基性岩の変質で生じやすく、低硬度の指標として使える。',
    rewardTag: 'stroke_count',
    rewardEvery: 12,
    science: {
      hardness: 1,
      crystalSystem: 'monoclinic',
      chemicalFormula: 'Mg₃Si₄O₁₀(OH)₂',
      luster: 'pearly',
      streakColor: '白',
      uses: 'チョークや化粧品の粉',
      funFact: '地球上で最もやわらかい鉱物で、触ると石とは思えないほど石鹸のようにすべすべした手触りがするよ。',
    },
  },
  {
    type: 'graphite',
    name: '石墨',
    nameEn: 'Graphite',
    imageFile: 'graphite.jpg',
    rank: 2,
    condition: '熟語の構成で正解16回ごと',
    description: '鉛筆の芯で有名な炭素鉱物。黒くやわらかい。',
    color: '#4F5458',
    genesis: 'metamorphic',
    formationDepth: 8,
    discoveryDepth: 8,
    geoNote: '有機物を含む堆積岩が変成を受けると石墨化しやすい。',
    rewardTag: 'compound_structure',
    rewardEvery: 16,
    science: {
      hardness: 2,
      crystalSystem: 'hexagonal',
      chemicalFormula: 'C',
      luster: 'metallic',
      streakColor: '黒',
      uses: '鉛筆の芯や潤滑剤',
      funFact: 'ダイヤモンドと同じ炭素だけでできているけれど、結びつき方が違うだけでこんなに黒くてやわらかくなるんだ。',
    },
  },
  {
    type: 'hematite',
    name: '赤鉄鉱',
    nameEn: 'Hematite',
    imageFile: 'hematite.jpg',
    rank: 2,
    condition: '画数で正解16回ごと',
    description: '赤褐色の条痕が特徴的な鉄鉱石。こすると赤い粉が出る。',
    color: '#8A3F35',
    genesis: 'hydrothermal',
    formationDepth: 6,
    discoveryDepth: 6,
    geoNote: '熱水沈殿や酸化作用で生成し、鉄鉱床の重要鉱物となる。',
    rewardTag: 'stroke_count',
    rewardEvery: 16,
    science: {
      hardness: 6,
      crystalSystem: 'trigonal',
      chemicalFormula: 'Fe₂O₃',
      luster: 'metallic',
      streakColor: '赤褐',
      uses: '鉄の原料や顔料',
      funFact: '石自体は黒っぽく見えても、削って粉にしたり紙にこすりつけたりすると、驚くほど鮮やかな赤色になるよ。',
    },
  },
  {
    type: 'galena',
    name: '方鉛鉱',
    nameEn: 'Galena',
    imageFile: 'galena.jpg',
    rank: 3,
    condition: '音訓で正解18回ごと',
    description: '立方体結晶が美しい鉛鉱物。ずっしり重い。',
    color: '#787980',
    genesis: 'hydrothermal',
    formationDepth: 6,
    discoveryDepth: 6,
    geoNote: '硫化鉱床に多く、閃亜鉛鉱と共生することが多い。',
    rewardTag: 'on_kun',
    rewardEvery: 18,
    science: {
      hardness: 3,
      crystalSystem: 'cubic',
      chemicalFormula: 'PbS',
      luster: 'metallic',
      streakColor: '灰黒',
      uses: '鉛の原料やはんだ',
      funFact: 'サイコロのような四角い結晶が特徴で、見た目以上にずっしりと重く、大昔はラジオの部品にも使われたよ。',
    },
  },
  {
    type: 'sphalerite',
    name: '閃亜鉛鉱',
    nameEn: 'Sphalerite',
    imageFile: 'sphalerite.jpg',
    rank: 3,
    condition: '送りがなで正解15回ごと',
    description: 'つやの強い亜鉛鉱物。色の幅が広く、褐色系が代表。',
    color: '#8A5C3F',
    genesis: 'hydrothermal',
    formationDepth: 6,
    discoveryDepth: 6,
    geoNote: '鉛亜鉛鉱床で主要な鉱石となり、方鉛鉱と共生しやすい。',
    rewardTag: 'okurigana',
    rewardEvery: 15,
    science: {
      hardness: 4,
      crystalSystem: 'cubic',
      chemicalFormula: '(Zn,Fe)S',
      luster: 'adamantine',
      streakColor: '白',
      uses: '亜鉛の原料',
      funFact: '鉄分が少ないとべっこう飴のように透き通って見え、ダイヤモンドにも負けないほどの強い光沢を放つよ。',
    },
  },
  {
    type: 'bornite',
    name: '斑銅鉱',
    nameEn: 'Bornite',
    imageFile: 'bornite.jpg',
    rank: 4,
    condition: '熟語作りで正解17回ごと',
    description: '表面が虹色に見えることがある銅鉱物。英語では peacock ore とも呼ばれる。',
    color: '#7F4C88',
    genesis: 'hydrothermal',
    formationDepth: 6,
    discoveryDepth: 6,
    geoNote: '銅硫化鉱床で黄銅鉱と共生し、酸化で多彩な色調を示す。',
    rewardTag: 'jukugo_making',
    rewardEvery: 17,
    science: {
      hardness: 3,
      crystalSystem: 'orthorhombic',
      chemicalFormula: 'Cu₅FeS₄',
      luster: 'metallic',
      streakColor: '灰黒',
      uses: '銅の原料',
      funFact: '掘り出した直後は赤銅色だけど、空気に触れるとすぐに紫や青の虹色に変わるので「孔雀銅」とも呼ばれるよ。',
    },
  },
  {
    type: 'native_copper',
    name: '自然銅',
    nameEn: 'Native Copper',
    imageFile: 'native_copper.jpg',
    rank: 4,
    condition: '対義語・類義語で正解22回ごと',
    description: '金属銅がそのまま見つかる標本。枝状や針金状の形が人気。',
    color: '#B87333',
    genesis: 'hydrothermal',
    formationDepth: 6,
    discoveryDepth: 5,
    transportReason: '熱水鉱床の上部酸化帯で再沈殿し、やや浅い層に濃集するため。',
    geoNote: '酸化還元環境の変化で二次的に自然銅が析出することがある。',
    rewardTag: 'antonym_synonym',
    rewardEvery: 22,
    science: {
      hardness: 3,
      crystalSystem: 'cubic',
      chemicalFormula: 'Cu',
      luster: 'metallic',
      streakColor: '銅赤',
      uses: '電線やコインの原料',
      funFact: '岩石の中から金属のままの姿で現れる珍しい石で、十円玉と同じ成分だから磨くとピカピカの10円色になるよ。',
    },
  },
  {
    type: 'native_gold',
    name: '自然金',
    nameEn: 'Native Gold',
    imageFile: 'native_gold.jpg',
    rank: 5,
    condition: '書き取りで「◎できた」かつ正解30回ごと',
    description: '金が自然のまま産する超人気標本。砂金として見つかることもある。',
    color: '#D4AF37',
    genesis: 'hydrothermal',
    formationDepth: 8,
    discoveryDepth: 4,
    transportReason: '深部鉱脈でできた金粒が風化で川に運ばれ、砂れき層に集まるため。',
    geoNote: '一次鉱床と二次砂鉱床の両方で産し、比重選鉱の教材にもなる。',
    rewardTag: 'writing',
    rewardEvery: 30,
    requirePerfectWriting: true,
    science: {
      hardness: 3,
      crystalSystem: 'cubic',
      chemicalFormula: 'Au',
      luster: 'metallic',
      streakColor: '金',
      uses: '貨幣や電子部品の回路',
      funFact: '非常に重くてやわらかく、薄く広げると1万分の1ミリという透けて見えるほどの「金箔」にできるんだよ。',
    },
  },
  {
    type: 'sulfur',
    name: '自然硫黄',
    nameEn: 'Sulfur',
    imageFile: 'sulfur.jpg',
    rank: 3,
    condition: '熟語作りで正解17回ごと',
    description: 'レモン色が目立つ鉱物。火山地帯の象徴として知られる。',
    color: '#F0D73D',
    genesis: 'magmatic',
    formationDepth: 11,
    discoveryDepth: 10,
    transportReason: '火山ガス由来の硫黄が冷えた割れ目で再結晶し、上部に沈着するため。',
    geoNote: '噴気孔周辺で生成し、火山活動の指標鉱物として扱われる。',
    rewardTag: 'jukugo_making',
    rewardEvery: 17,
    science: {
      hardness: 2,
      crystalSystem: 'orthorhombic',
      chemicalFormula: 'S',
      luster: 'resinous',
      streakColor: '白',
      uses: 'マッチやゴムの添加物',
      funFact: '火山近くの温泉などで見つかる黄色い石で、燃やすと青い炎が出て、鼻をつく独特のツンとした臭いがするよ。',
    },
  },
  {
    type: 'cinnabar',
    name: '辰砂',
    nameEn: 'Cinnabar',
    imageFile: 'cinnabar.jpg',
    rank: 4,
    condition: '同音異義語で正解20回ごと',
    description: '鮮やかな赤色が強い印象を残す水銀鉱物。',
    color: '#C43B33',
    genesis: 'hydrothermal',
    formationDepth: 6,
    discoveryDepth: 6,
    geoNote: '低温熱水鉱床で産し、色彩の強さから教材映えしやすい。',
    rewardTag: 'homophone',
    rewardEvery: 20,
    science: {
      hardness: 3,
      crystalSystem: 'trigonal',
      chemicalFormula: 'HgS',
      luster: 'adamantine',
      streakColor: '朱',
      uses: '水銀の原料や朱色の顔料',
      funFact: '「赤い金」とも呼ばれ、古くから神社やお寺の鳥居を塗る鮮やかな朱色の絵の具として大切にされてきたよ。',
    },
  },
  {
    type: 'azurite',
    name: '藍銅鉱',
    nameEn: 'Azurite',
    imageFile: 'azurite.jpg',
    rank: 4,
    condition: '読みで正解20回ごと',
    description: '濃い青色が印象的な二次銅鉱物。孔雀石と並んで人気。',
    color: '#2D63C8',
    genesis: 'hydrothermal',
    formationDepth: 6,
    discoveryDepth: 6,
    geoNote: '銅鉱床の酸化帯で孔雀石と共生し、色相で識別しやすい。',
    rewardTag: 'reading',
    rewardEvery: 20,
    science: {
      hardness: 4,
      crystalSystem: 'monoclinic',
      chemicalFormula: 'Cu₃(CO₃)₂(OH)₂',
      luster: 'vitreous',
      streakColor: '青',
      uses: '宝石や絵の具の青い顔料',
      funFact: '吸い込まれるような深い青色が特徴で、長い年月をかけて水分を吸うと、緑色の孔雀石に変化してしまうんだ。',
    },
  },
  {
    type: 'rhodochrosite',
    name: '菱マンガン鉱',
    nameEn: 'Rhodochrosite',
    imageFile: 'rhodochrosite.jpg',
    rank: 4,
    condition: '対義語・類義語で正解20回ごと',
    description: 'ピンク色の縞が美しいマンガン鉱物。',
    color: '#D67691',
    genesis: 'hydrothermal',
    formationDepth: 7,
    discoveryDepth: 7,
    geoNote: '炭酸塩鉱物として熱水脈に産し、縞模様標本がコレクション向き。',
    rewardTag: 'antonym_synonym',
    rewardEvery: 20,
    science: {
      hardness: 4,
      crystalSystem: 'trigonal',
      chemicalFormula: 'MnCO₃',
      luster: 'vitreous',
      streakColor: '白',
      uses: 'マンガンの原料や宝石',
      funFact: '断面がバラの花のように見えることから「インカローズ」と呼ばれ、昔から愛情を象徴する石として愛されたよ。',
    },
  },
  {
    type: 'rhodonite',
    name: '薔薇輝石',
    nameEn: 'Rhodonite',
    imageFile: 'rhodonite.jpg',
    rank: 4,
    condition: '熟語の構成で正解20回ごと',
    description: 'ピンク地に黒い筋が入るのが特徴。磨くと模様が映える。',
    color: '#BC6A7C',
    genesis: 'metamorphic',
    formationDepth: 8,
    discoveryDepth: 8,
    geoNote: 'マンガンを含む変成環境で形成され、黒色脈は酸化鉱物由来。',
    rewardTag: 'compound_structure',
    rewardEvery: 20,
    science: {
      hardness: 6,
      crystalSystem: 'triclinic',
      chemicalFormula: '(Mn,Ca)₅Si₅O₁₅',
      luster: 'vitreous',
      streakColor: '白',
      uses: '装飾品や彫刻の材料',
      funFact: 'ギリシャ語の「バラ（ロドン）」が名前の由来で、黒い模様が混ざることでピンク色がより引き立って見えるよ。',
    },
  },
  {
    type: 'tourmaline',
    name: '電気石',
    nameEn: 'Tourmaline',
    imageFile: 'tourmaline.jpg',
    rank: 3,
    condition: '三字熟語で正解20回ごと',
    description: '多彩な色をもつホウ素鉱物。帯電性の話題で理科との相性が良い。',
    color: '#1F2C2F',
    genesis: 'magmatic',
    formationDepth: 9,
    discoveryDepth: 9,
    geoNote: 'ペグマタイトや熱水脈で生成し、組成変化で色が大きく変わる。',
    rewardTag: 'three_char_compound',
    rewardEvery: 20,
    science: {
      hardness: 8,
      crystalSystem: 'trigonal',
      chemicalFormula: '(Na,Ca)(Li,Mg,Al)₃(Al,Fe,Mn)₆(BO₃)₃(Si₆O₁₈)(OH)₄',
      luster: 'vitreous',
      streakColor: '白',
      uses: '健康器具や精密機器',
      funFact: '熱を加えたり圧力をかけたりすると電気が流れる不思議な性質があり、日本では「電気石」と呼ばれているよ。',
    },
  },
  {
    type: 'opal',
    name: 'オパール',
    nameEn: 'Opal',
    imageFile: 'opal.jpg',
    rank: 4,
    condition: '音訓で正解22回ごと',
    description: '虹色の遊色が人気の準鉱物。結晶質ではない点も学習ポイント。',
    color: '#CFE9E8',
    genesis: 'sedimentary',
    formationDepth: 4,
    discoveryDepth: 4,
    geoNote: 'シリカゲルの沈殿でできる非晶質物質で、厳密には準鉱物扱い。',
    rewardTag: 'on_kun',
    rewardEvery: 22,
    science: {
      hardness: 6,
      crystalSystem: 'amorphous',
      chemicalFormula: 'SiO₂·nH₂O',
      luster: 'vitreous',
      streakColor: '白',
      uses: '宝石や装飾品',
      funFact: '内部に閉じ込められた光が虹のようにキラキラ輝く「遊色効果」が見られ、実は成分の10％ほどが水なんだよ。',
    },
  },
  {
    type: 'nephrite',
    name: '軟玉',
    nameEn: 'Nephrite',
    imageFile: 'nephrite.jpg',
    rank: 4,
    condition: '熟語の構成で正解24回ごと',
    description: '繊維状結晶が絡み合って丈夫なヒスイ系鉱物。',
    color: '#4A8F76',
    genesis: 'metamorphic',
    formationDepth: 8,
    discoveryDepth: 3,
    transportReason: '深部の変成帯で形成された岩塊が隆起し、川原の転石として現れるため。',
    geoNote: '単結晶ではなく集合体として産し、ねばり強い物性を示す。',
    rewardTag: 'compound_structure',
    rewardEvery: 24,
    science: {
      hardness: 7,
      crystalSystem: 'monoclinic',
      chemicalFormula: 'Ca₂(Mg,Fe)₅Si₈O₂₂(OH)₂',
      luster: 'vitreous',
      streakColor: '白',
      uses: '彫刻や工芸品',
      funFact: 'ヒスイに似ているけれど別の鉱物で、細い結晶がフェルトのように複雑に絡み合っているからとても頑丈なんだよ。',
    },
  },
  {
    type: 'turquoise',
    name: 'トルコ石',
    nameEn: 'Turquoise',
    imageFile: 'turquoise.jpg',
    rank: 5,
    condition: '同音異義語で正解24回ごと',
    description: '空色から青緑色まで見せる人気鉱物。装飾用途でも有名。',
    color: '#3AAFB9',
    genesis: 'hydrothermal',
    formationDepth: 6,
    discoveryDepth: 5,
    transportReason: '銅鉱床上部の酸化帯で形成され、やや浅い層に集中するため。',
    geoNote: 'リン酸塩の二次鉱物として乾燥環境で生成し、化学風化の影響を受けやすい。',
    rewardTag: 'homophone',
    rewardEvery: 24,
    science: {
      hardness: 6,
      crystalSystem: 'triclinic',
      chemicalFormula: 'CuAl₆(PO₄)₄(OH)₈·4H₂O',
      luster: 'waxy',
      streakColor: '白',
      uses: '宝石やトルコ石細工',
      funFact: 'トルコを経由してヨーロッパに伝わったことが名前の由来で、晴れ渡った空のような青色が勇気の象徴とされるよ。',
    },
  },
  {
    type: 'barite',
    name: '重晶石',
    nameEn: 'Barite',
    imageFile: 'barite.jpg',
    rank: 3,
    condition: '読みで正解22回ごと',
    description: '見た目以上に重い硫酸塩鉱物。重さの比較教材に使いやすい。',
    color: '#E3E2DF',
    genesis: 'hydrothermal',
    formationDepth: 6,
    discoveryDepth: 6,
    geoNote: '熱水脈で硫酸イオンと結びつき析出し、比重が高い。',
    rewardTag: 'reading',
    rewardEvery: 22,
    science: {
      hardness: 3,
      crystalSystem: 'orthorhombic',
      chemicalFormula: 'BaSO₄',
      luster: 'vitreous',
      streakColor: '白',
      uses: '造影剤（バリウム）や重し',
      funFact: '見た目よりもずっと重いのが特徴で、健康診断で飲む「バリウム」の原料としても使われている身近な石だよ。',
    },
  },
  {
    type: 'celestite',
    name: '天青石',
    nameEn: 'Celestite',
    imageFile: 'celestite.jpg',
    rank: 4,
    condition: '同音異義語で正解26回ごと',
    description: '淡い青色が空を思わせる硫酸塩鉱物。',
    color: '#8DC0E8',
    genesis: 'sedimentary',
    formationDepth: 5,
    discoveryDepth: 5,
    geoNote: '海成堆積層や蒸発岩で産し、色名由来の学習ネタとして扱いやすい。',
    rewardTag: 'homophone',
    rewardEvery: 26,
    science: {
      hardness: 4,
      crystalSystem: 'orthorhombic',
      chemicalFormula: 'SrSO₄',
      luster: 'vitreous',
      streakColor: '白',
      uses: '花火の着色剤（赤）の原料',
      funFact: '「天の空色」という意味の名前を持ち、美しい青い結晶は花火を真っ赤に光らせるための材料にもなっているよ。',
    },
  },
  {
    type: 'halite',
    name: '岩塩',
    nameEn: 'Halite',
    imageFile: 'halite.jpg',
    rank: 4,
    condition: '部首で正解15回ごと',
    description: '食塩の結晶版。立方体の形が観察しやすい。',
    color: '#F2F5FA',
    genesis: 'sedimentary',
    formationDepth: 3,
    discoveryDepth: 3,
    geoNote: '塩湖や閉鎖海盆での蒸発により析出する代表的蒸発岩鉱物。',
    rewardTag: 'radical',
    rewardEvery: 15,
    science: {
      hardness: 3,
      crystalSystem: 'cubic',
      chemicalFormula: 'NaCl',
      luster: 'vitreous',
      streakColor: '白',
      uses: '食塩の原料や道路の融雪剤',
      funFact: '大昔の海が干上がってできた塩の結晶で、なめるとしょっぱいよ。綺麗な立方体の形で、叩くとパカッと割れるよ。',
    },
  },
  {
    type: 'dolomite',
    name: '苦灰石',
    nameEn: 'Dolomite',
    imageFile: 'dolomite.jpg',
    rank: 2,
    condition: '画数で正解15回ごと',
    description: '方解石に似るが反応性が異なる炭酸塩鉱物。見分け学習向き。',
    color: '#DAD7C8',
    genesis: 'sedimentary',
    formationDepth: 7,
    discoveryDepth: 7,
    geoNote: 'ドロマイト化作用で形成され、炭酸塩岩の環境復元に使われる。',
    rewardTag: 'stroke_count',
    rewardEvery: 15,
    science: {
      hardness: 4,
      crystalSystem: 'trigonal',
      chemicalFormula: 'CaMg(CO₃)₂',
      luster: 'vitreous',
      streakColor: '白',
      uses: '建築材料や肥料',
      funFact: '方解石にとてもよく似ているけれど、酸をかけてもすぐには泡を出さない、少し我慢強い（？）性質があるんだよ。',
    },
  },
  {
    type: 'aragonite',
    name: '霰石',
    nameEn: 'Aragonite',
    imageFile: 'aragonite.jpg',
    rank: 3,
    condition: '送りがなで正解15回ごと',
    description: '方解石と同じ化学式でも結晶構造が異なる鉱物。',
    color: '#E7E8E4',
    genesis: 'sedimentary',
    formationDepth: 7,
    discoveryDepth: 7,
    geoNote: '貝殻やサンゴ骨格に含まれ、環境変化で方解石へ転移しやすい。',
    rewardTag: 'okurigana',
    rewardEvery: 15,
    science: {
      hardness: 4,
      crystalSystem: 'orthorhombic',
      chemicalFormula: 'CaCO₃',
      luster: 'vitreous',
      streakColor: '白',
      uses: '装飾品や水槽の砂',
      funFact: '方解石と同じ成分だけど形が違い、真珠の内側のキラキラした輝きや貝殻も、実はこの霰石でできているんだよ。',
    },
  },
  {
    type: 'epidote',
    name: '緑簾石',
    nameEn: 'Epidote',
    imageFile: 'epidote.jpg',
    rank: 3,
    condition: '熟語の構成で正解24回ごと',
    description: '緑色の柱状結晶が特徴。変成帯の指標鉱物。',
    color: '#6F8F3D',
    genesis: 'metamorphic',
    formationDepth: 8,
    discoveryDepth: 8,
    geoNote: '低〜中温変成作用や熱水変質帯で生成し、変質評価に有効。',
    rewardTag: 'compound_structure',
    rewardEvery: 24,
    science: {
      hardness: 7,
      crystalSystem: 'monoclinic',
      chemicalFormula: 'Ca₂Al₂Fe(SiO₄)(Si₂O₇)O(OH)',
      luster: 'vitreous',
      streakColor: '白',
      uses: '宝石や地質調査の資料',
      funFact: '濃い緑色が特徴で、結晶がすだれ（簾）を並べたように見えることから、日本では「緑簾石」と呼ばれるよ。',
    },
  },
  {
    type: 'prehnite',
    name: 'ぶどう石',
    nameEn: 'Prehnite',
    imageFile: 'prehnite.jpg',
    rank: 3,
    condition: '熟語作りで正解17回ごと',
    description: 'ぶどう房のような集合体で見つかることが多い淡緑色鉱物。',
    color: '#9CCF9A',
    genesis: 'hydrothermal',
    formationDepth: 7,
    discoveryDepth: 7,
    geoNote: '低温熱水作用で晶出し、空隙充填鉱物として産出する。',
    rewardTag: 'jukugo_making',
    rewardEvery: 17,
    science: {
      hardness: 7,
      crystalSystem: 'orthorhombic',
      chemicalFormula: 'Ca₂Al₂Si₃O₁₀(OH)₂',
      luster: 'vitreous',
      streakColor: '白',
      uses: '宝石や装飾品',
      funFact: '結晶が丸く集まって産出する姿がマスカットの粒のように見えることから、日本では「ぶどう石」と呼ばれるよ。',
    },
  },
  {
    type: 'kyanite',
    name: '藍晶石',
    nameEn: 'Kyanite',
    imageFile: 'kyanite.jpg',
    rank: 4,
    condition: '三字熟語で正解24回ごと',
    description: '方向によって硬さが変わる不思議な変成鉱物。青色結晶が特徴。',
    color: '#3D6FB0',
    genesis: 'metamorphic',
    formationDepth: 8,
    discoveryDepth: 9,
    transportReason: '高圧変成帯で生成した藍晶石が、断層運動で上位の岩体境界へ露出するため。',
    geoNote: '高圧変成条件を示す指標鉱物で、変成相解析に使われる。',
    rewardTag: 'three_char_compound',
    rewardEvery: 24,
    science: {
      hardness: 7,
      crystalSystem: 'triclinic',
      chemicalFormula: 'Al₂SiO₅',
      luster: 'vitreous',
      streakColor: '白',
      uses: '耐火製品や宝石',
      funFact: '縦方向には硬いけれど横方向にはやわらかいという珍しい性質があり、そのことから「二硬石」とも呼ばれるよ。',
    },
  },
  {
    type: 'andalusite',
    name: '紅柱石',
    nameEn: 'Andalusite',
    imageFile: 'andalusite.jpg',
    rank: 4,
    condition: '対義語・類義語で正解24回ごと',
    description: '断面に十字模様が出るタイプがあり、標本人気が高い。',
    color: '#8C6A4A',
    genesis: 'metamorphic',
    formationDepth: 8,
    discoveryDepth: 8,
    geoNote: '接触変成の指標鉱物で、圧力条件の違いを読み解く手がかりになる。',
    rewardTag: 'antonym_synonym',
    rewardEvery: 24,
    science: {
      hardness: 8,
      crystalSystem: 'orthorhombic',
      chemicalFormula: 'Al₂SiO₅',
      luster: 'vitreous',
      streakColor: '白',
      uses: '耐火レンガの材料',
      funFact: '結晶の中に炭素が入り込んで黒い十字模様が見えるものがあり、昔は「十字石」としてお守りにされたよ。',
    },
  },
  {
    type: 'scheelite',
    name: '灰重石',
    nameEn: 'Scheelite',
    imageFile: 'scheelite.jpg',
    rank: 4,
    condition: '三字熟語で正解25回ごと',
    description: '紫外線で蛍光を示すことがあるタングステン鉱物。',
    color: '#E7D9A7',
    genesis: 'hydrothermal',
    formationDepth: 9,
    discoveryDepth: 9,
    geoNote: 'スカルン鉱床で産し、タングステン資源として工業的にも重要。',
    rewardTag: 'three_char_compound',
    rewardEvery: 25,
    science: {
      hardness: 5,
      crystalSystem: 'tetragonal',
      chemicalFormula: 'CaWO₄',
      luster: 'adamantine',
      streakColor: '白',
      uses: 'タングステンの原料',
      funFact: '見た目は地味な石だけど、暗闇で紫外線を当てると青白く美しく光る、とてもドラマチックな一面を持っているよ。',
    },
  },
  {
    type: 'molybdenite',
    name: '輝水鉛鉱',
    nameEn: 'Molybdenite',
    imageFile: 'molybdenite.jpg',
    rank: 4,
    condition: '書き取りで正解26回ごと',
    description: '石墨に似た金属光沢を持つモリブデン鉱物。',
    color: '#5F646A',
    genesis: 'hydrothermal',
    formationDepth: 9,
    discoveryDepth: 9,
    geoNote: '花崗岩関連の熱水系で産し、高温鉱化作用の指標となる。',
    rewardTag: 'writing',
    rewardEvery: 26,
    science: {
      hardness: 2,
      crystalSystem: 'hexagonal',
      chemicalFormula: 'MoS₂',
      luster: 'metallic',
      streakColor: '灰黒',
      uses: '潤滑剤や特殊鋼の原料',
      funFact: '鉛色で金属の光沢があり、触ると手が黒くなるほどやわらかいよ。機械をスムーズに動かす油の代わりにもなるよ。',
    },
  },
  {
    type: 'chromite',
    name: 'クロム鉄鉱',
    nameEn: 'Chromite',
    rank: 4,
    condition: '書き取りで正解22回ごと',
    description: '超塩基性マグマから直接結晶化するクロムの鉱石。マントルの代表的な鉱物。',
    color: '#2C2C2C',
    genesis: 'magmatic',
    formationDepth: 11,
    discoveryDepth: 10,
    transportReason: 'マントル由来の超塩基性岩体が地殻変動で押し上げられ、かんらん岩中に産するため。',
    geoNote: '超塩基性マグマから橄欖石とともに初期晶出し、層状貫入岩体に濃集する。',
    rewardTag: 'writing',
    rewardEvery: 22,
    science: {
      hardness: 6,
      crystalSystem: 'cubic',
      chemicalFormula: 'FeCr₂O₄',
      luster: 'metallic',
      streakColor: '暗褐',
      uses: 'ステンレス鋼や耐火材の原料',
      funFact: '橄欖石と一緒にマントルの深いところで生まれる仲間で、ステンレスの「さびない力」はこの石のクロムのおかげなんだよ。',
    },
  },
  {
    type: 'spinel',
    name: 'スピネル',
    nameEn: 'Spinel',
    rank: 4,
    condition: '書き取りで正解24回ごと',
    description: '八面体の美しい結晶が特徴。ルビーと間違えられた歴史を持つ宝石鉱物。',
    color: '#C8102E',
    genesis: 'magmatic',
    formationDepth: 11,
    discoveryDepth: 10,
    transportReason: 'マグマ中で高温結晶化したスピネルが、火山噴出物に乗って上部層へ運ばれるため。',
    geoNote: '高温マグマ中で直接結晶化し、かんらん岩やキンバーライトに産する深部鉱物。',
    rewardTag: 'writing',
    rewardEvery: 24,
    science: {
      hardness: 8,
      crystalSystem: 'cubic',
      chemicalFormula: 'MgAl₂O₄',
      luster: 'vitreous',
      streakColor: '白',
      uses: '宝石や耐火レンガの材料',
      funFact: 'イギリス王冠の「黒太子のルビー」は実はスピネルだった！ 本物のルビーと長い間間違えられていた美しい石だよ。',
    },
  },
  {
    type: 'fossil',
    name: '化石標本',
    nameEn: 'Fossil',
    imageFile: 'fossil.jpg',
    rank: 6,
    condition: '一度ミス → 3連続正解で克服',
    description: '大昔の生き物の痕跡。ミスから復活した証。研究者にとって最もストーリーがある標本。',
    color: '#8B8378',
    genesis: 'sedimentary',
    formationDepth: 2,
    discoveryDepth: 2,
    geoNote: '化石は鉱物そのものではなく、生物の痕跡が堆積層で保存されたもの。',
    science: {
      hardness: null,
      crystalSystem: 'none',
      chemicalFormula: '(様々)',
      luster: 'earthy',
      streakColor: '(様々)',
      uses: '昔の生き物や環境を調べる手がかり',
      funFact: '何千万年も前の生き物が石になったもので、大昔の地球がどんな姿だったのかを教えてくれる貴重なメッセンジャーだよ。',
    },
  },
];

export const MINERAL_BY_TYPE: Record<MineralType, MineralDef> = Object.fromEntries(
  MINERALS.map(m => [m.type, m])
) as Record<MineralType, MineralDef>;
